### ISSUE TITLE
💡 Create Uploading audio file to storage method

### ISSUE THREAD

**Issue by aoiorio** [aoiorio/VolcanoAPI#22]
## 🥴 What do you want to do?
- I want to create a function that can upload an audio file to storage
<br>

## 🐌 Purpose
- For create POST method on FastAPI, on top of that if I don't do that, I won't be able to create my application.
<br>

## 🎩 Images
Nothing
<br>

## 🌋 TODOs
- [x] Create function called upload_audio_file
- [x] Create feature that can get public absolute url of the audio_file
- [x] Add the url to audio_url column in database in repository file

**Comment by aoiorio** [comment]
I think it's the best service to use.
Please look at [this](https://tebi.io/index.html#prices)

**Comment by aoiorio** [comment]
![LGTM](https://image.lgtmoon.dev/186856)
