### ISSUE TITLE
💡 Create AWS Lambda Function & Create CI

### ISSUE THREAD

**Issue by aoiorio** [aoiorio/VolcanoAPI#4]
## 🥴 What do you want to do?
- Create AWS Lambda Function and Create CI for deployment of zip file to it
<br>

## 🐌 Purpose
- It'll be useful to deploy
<br>

## 🎩 Images
Nothing
<br>

## 🌋 TODO
- [x] Create AWS Lambda Function called "volcano"
- [x] Create AWS API Gateway and connect to Lambda
- [x] Create GitHub Actions for deploying zip file to Lambda

**Comment by aoiorio** [comment]
![LGTM](https://image.lgtmoon.dev/226032)
