### ISSUE TITLE
💡 Create Get Goal Feature

### ISSUE THREAD

**Issue by aoiorio** [aoiorio/VolcanoAPI#40]
## 🥴 What do you want to do?
- I want to create Get Goal feature that can get the percentage of todos
<br>

## 🐌 Purpose
- for recognizing progress of todo
<br>

## 🎩 Images
Nothing
<br>

## 🌋 TODOs
- [x] Create getGoal method in domain
- [x] Create getGoal method in repository
- [x] Create getGoal method in use case
- [x] Create getGoal endpoint

**Comment by aoiorio** [comment]
![LGTM](https://raw.githubusercontent.com/yoshi389111/yoshi389111/main/LGTM/LGTM_github_contribute_light.png)
