### ISSUE TITLE
💡 Create SignIn, SignUp and SignOut Features

### ISSUE THREAD

**Issue by aoiorio** [aoiorio/VolcanoAPI#8]
## 🥴 What do you want to do?
- Create Authorization features
<br>

## 🐌 Purpose
- For user experiences
<br>

## 🎩 Images
Nothing
<br>

## 🌋 TODOs
- [x] Create SignIn feature
- [x] Create SignUp feature
- [x] Create SignOut feature
- [x] Create Front-End by using Flutter
- [x] Connect to DB

<br>

## 🐻‍❄️ Related Product Goal
- [Product Goal Amazing](https://sharing.clickup.com/9018292617/t/h/86epcupwn/C55NBA2IS0ZSQFD)

**Comment by aoiorio** [comment]
## 🎫 Tickets
[One of Authentication GitHub Issue](https://github.com/aoiorio/Volcano/issues/4)

**Comment by aoiorio** [comment]
![LGTM](https://image.lgtmoon.dev/186856)
